_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 91.7578
  - 72.9196
  - 2
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 16
minzoom: 0
name: ''
source: "tmsource:///Users/KyleK/github/ruralwater/mapbox/loudounfire.tm2source"
styles: 
  - style.mss
template: ''
