_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -77.6733
  - 39.0762
  - 11
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 16
minzoom: 11
name: ''
source: "mapbox:///mappiskyle.38c2175b"
styles: 
  - style.mss
template: ''
